version: '3.1'

services:
  sadb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  sa:
    image: sa
    command: tail -F /var/logs
    ports:
      - 9065:9065

# networks:
#   default:
